### ISSUE TITLE
[Bug] Doesn't compile with iOS 13

### ISSUE THREAD

**Issue by ksilz** [rurico/flutter_video_compress#59]
### Description
I'm using flutter_video_compress: 0.3.7+8 to deploy to an iPhone XS Max on iOS 13. It works in the Android simulator, but I get the following compilation errors in Xcode 11:

```
Xcode's output:
↳
    leveldb-library-fugunjpkrwxlsrdkdyyylozzzgaq
    /Users/karsten/workspaces/me/services/company-c/apps/ca_test_flutter/ios/Pods/Regift/Regift/AVAssetImageGeneratorTimePoints.swift:12:5: warning: 'public' modifier is redundant for instance method declared in a public extension
        public func generateCGImagesAsynchronouslyForTimePoints(timePoints: [TimePoint], completionHandler: @escaping AVAssetImageGeneratorCompletionHandler) {
        ^~~~~~~

    leveldb-library-fugunjpkrwxlsrdkdyyylozzzgaq
    /Users/karsten/workspaces/me/services/company-c/apps/ca_test_flutter/ios/Pods/Regift/Regift/Regift.swift:251:45: error: missing argument label 'preferredTimescale:' in call
                let time = CMTimeMakeWithSeconds(seconds, Constants.TimeInterval)
                                                ^
                                                          preferredTimescale: 
    /Users/karsten/workspaces/me/services/company-c/apps/ca_test_flutter/ios/Pods/Regift/Regift/Regift.swift:303:46: error: missing argument label 'preferredTimescale:' in call
            let tolerance = CMTimeMakeWithSeconds(Constants.Tolerance, Constants.TimeInterval)
                                                 ^
                                                                       preferredTimescale: 
    /Users/karsten/workspaces/me/services/company-c/apps/ca_test_flutter/ios/Pods/Regift/Regift/Regift.swift:251:45: error: missing argument label 'preferredTimescale:' in call
                let time = CMTimeMakeWithSeconds(seconds, Constants.TimeInterval)
                                                ^
                                                          preferredTimescale: 
    /Users/karsten/workspaces/me/services/company-c/apps/ca_test_flutter/ios/Pods/Regift/Regift/Regift.swift:303:46: error: missing argument label 'preferredTimescale:' in call
            let tolerance = CMTimeMakeWithSeconds(Constants.Tolerance, Constants.TimeInterval)
                                                 ^
                                                                       preferredTimescale: 
    /Users/karsten/workspaces/me/services/company-c/apps/ca_test_flutter/ios/Pods/Regift/Regift/AVAssetImageGeneratorTimePoints.swift:12:5: warning: 'public' modifier is redundant for instance method declared in a public extension
        public func generateCGImagesAsynchronouslyForTimePoints(timePoints: [TimePoint], completionHandler: @escaping AVAssetImageGeneratorCompletionHandler) {
        ^~~~~~~

    leveldb-library-fugunjpkrwxlsrdkdyyylozzzgaq
    note: Using new build systemnote: Planning buildnote: Constructing build description

Could not build the precompiled application for the device.

Error launching application on o8z.
```

### Platform
iOS

### Backtracking step (if has)
  1. Include `flutter_video_compress: 0.3.7+8` in `pubspec.yaml`
  2. Build with Flutter 1.9 & Xcode 11
  3. Get Compilation error 

### Expected solution
This project uses the Regift iOS Cocoa Pod, I think in version 1.5. Now in version 1.6, these problems are solved. So I added this line to my `ios/Podfile`:

```
pod 'Regift', '1.6'
```

But Regift 1.6 has iOS 11.1 as the minimum requirement. This clashes with the rest of Flutter  which has iOS 8.0 as the minimum compilation target. I'm unable to change that to iOS 11.1. I can change the deployment target to 11.1, but that hasn't solved the error.

**Comment by evaschalde** [comment]
Is there any news about this?? I have the same issue and the solution of fixing it with xcode every time pubspec runs is not good enough for me

**Comment by nthungdev** [comment]
> Is there any news about this?? I have the same issue and the solution of fixing it with xcode every time pubspec runs is not good enough for me

I had to migrate to this package: https://pub.dev/packages/video_compress
It's still new and does the same thing, but no problem so far.

**Comment by evaschalde** [comment]
> > Is there any news about this?? I have the same issue and the solution of fixing it with xcode every time pubspec runs is not good enough for me
> 
> I had to migrate to this package: https://pub.dev/packages/video_compress
> It's still new and does the same thing, but no problem so far.

Testing it!

**Comment by evaschalde** [comment]
> > > Is there any news about this?? I have the same issue and the solution of fixing it with xcode every time pubspec runs is not good enough for me
> > 
> > 
> > I had to migrate to this package: https://pub.dev/packages/video_compress
> > It's still new and does the same thing, but no problem so far.
> 
> Testing it!

Works for me! Thanks @nthungdev !!!!

**Comment by evaschalde** [comment]
> > Is there any news about this?? I have the same issue and the solution of fixing it with xcode every time pubspec runs is not good enough for me
> 
> I had to migrate to this package: https://pub.dev/packages/video_compress
> It's still new and does the same thing, but no problem so far.

I'm getting an error, if I preview the video before compressing it I get "PlatformException(error, java.io.IOException: Failed to instantiate extractor., null)", could this be because of the preview theart that doesn't allow me to open the video again?

**Comment by nthungdev** [comment]
> I'm getting an error, if I preview the video before compressing it I get "PlatformException(error, java.io.IOException: Failed to instantiate extractor., null)", could this be because of the preview theart that doesn't allow me to open the video again?

Possibly. Are you able to open the video after the compression?

**Comment by evaschalde** [comment]
Once I preview the video with native camera preview I’m unable to compress,
I get this error: PlatformException(error, java.io.IOException: Failed to
instantiate extractor., null). I tried to make a copy of the video, but
still fails

**Comment by jhihruei** [comment]
Same issue here, and seems duplicate with #56?

**Comment by afnx** [comment]
The problem still persists. Running the project on Xcode and fixing relevant errors worked, but sometimes I needed to repeat the process. Will there be any update to fix this?

**Comment by festapp86** [comment]
Also after upgrading to flutter 1.22 and iOS 14, this version is not working anymore (flutter build ios throws a lot of errors. Android worked)

**Comment by jpetro416** [comment]
This error still exists and I can't build on IOS now
